name: commander_cli
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^8.0.0
  args: ^2.7.0
  commander_ui: ^2.4.0
  json2yaml: ^3.0.1
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

commander_cli:
  includes:
    - lib/src/application/commands
  commands:
    - name: generate
      description: Generate commands
      entrypoint: lib/src/application/commands/generate.dart
