name: commander_cli
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^8.0.0
  args: ^2.7.0
  json2yaml: ^3.0.1
  path: ^1.9.1
  vine: ^1.7.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

my_package:
  includes:
    - lib/src/application/commands
  commands:
    - name: foo
      description: Foo command
      entrypoint: lib/src/application/commands/foo.dart
      args:
        - test
        - age
      flags:
        - name: verbose
          abbr: v
          help: Verbose mode
      options:
        - name: color
          abbr: c
          help: Color mode
        - name: name
          abbr: n
          help: Name mode
    - name: generate
      description: Generate commands
      entrypoint: lib/src/application/commands/generate.dart
